const fs = require('fs');
const existingModules = JSON.parse(fs.readFileSync('src/data/modules.json', 'utf8'));
const newIds = ['airflow-hooks','airflow-connections','airflow-scheduling','airflow-retries','airflow-taskflow',
  'airflow-xcom','airflow-pools','airflow-trigger-rules','airflow-backfill','airflow-catchup','airflow-prod-best-practices',
  'kafka-topics','kafka-replication','kafka-producer','kafka-consumer','kafka-consumer-groups','kafka-offsets',
  'kafka-schema-registry','kafka-connect','debezium','spark-streaming-kafka',
  'aws-glue','aws-athena','aws-lambda','aws-emr','aws-lake-formation','aws-cloudwatch','aws-cost-optimization',
  'docker-compose','monitoring','logging','env-vars',
  'project-python-etl','project-spark-analytics','project-aws-pipeline','project-airflow-pipeline',
  'project-kafka-streaming','project-lakehouse','project-e2e',
  'sys-design-capacity','sys-design-batch','sys-design-streaming','sys-design-cdc','sys-design-warehouse',
  'sys-design-lakehouse','sys-design-netflix','sys-design-uber','sys-design-fraud','sys-design-iot',
  'interview-spark','interview-kafka','interview-airflow','interview-aws','interview-modeling',
  'interview-sysdesign','interview-resume','interview-mock','interview-company'];
const filtered = existingModules.filter(m => !newIds.includes(m.id));

const T = (id,title,phase,phaseLabel,desc,diff,hours,imp,iw,cl,ii,pi,ir,prereqs,los,prob,why,rw,theory,res,mini,ex,next,prev,cm,iq,fc,sum) => ({
  id,title,phase,phaseLabel,description:desc,difficulty:diff,estimatedHours:hours,importance:imp,interviewWeight:iw,
  careerLevel:cl,interviewImportance:ii,productionImportance:pi,interviewRecommendation:ir,
  prerequisites:prereqs,learningObjectives:los,problemItSolves:prob,whyItExists:why,realWorldUsage:rw,
  theory,resources:res||{docs:[],youtube:[],udemy:[],articles:[]},miniProject:mini,exercises:ex,
  nextTopics:next,previousTopics:prev,commonMistakes:cm,interviewQuestions:iq,flashcards:fc,summary:sum
});
const R = {docs:[],youtube:[],udemy:[],articles:[]};

const newModules = [
// ═══ AIRFLOW EXPANSION ═══
T("airflow-hooks","Airflow Hooks & Connections","orchestration","Orchestration","Hooks provide interfaces to external systems (databases, APIs, cloud). Connections store credentials.","intermediate",1,"good-to-know",2,"junior",2,4,"Know Concept",["airflow-intro"],["Define hooks","Configure connections in Airflow UI","Use hooks in custom operators"],"Your Airflow DAG needs to connect to Postgres, S3, and Slack. Without hooks, you'd hardcode credentials. Hooks + Connections centralize this.","Hooks abstract away the complexity of connecting to external systems. Connections store the credentials securely.","Every Airflow deployment uses connections. The most common: PostgresHook, S3Hook, SlackHook.","## Hooks & Connections\n\n### Connections\nStored in Airflow's metadata database. Configure via UI: Admin > Connections.\n```\nConn ID: my_postgres\nConn Type: Postgres\nHost: db.example.com\nSchema: analytics\nLogin: airflow_user\nPassword: ****\nPort: 5432\n```\n\n### Using Hooks\n```python\nfrom airflow.providers.postgres.hooks.postgres import PostgresHook\n\nhook = PostgresHook(postgres_conn_id='my_postgres')\ndf = hook.get_pandas_df('SELECT * FROM orders')\n```",R,null,[],["operators"],["airflow-intro"],["Hardcoding credentials in DAG files"],["What is an Airflow Hook?","How do Connections work?"],
[{front:"Airflow Hook vs Connection?",back:"Connection: stores credentials (conn_id, host, login, password). Hook: Python class that uses a Connection to interact with an external system (PostgresHook, S3Hook)."}],"Hooks provide Python interfaces to external systems. Connections store credentials securely. Configure connections in Airflow UI."),

T("airflow-taskflow","TaskFlow API","orchestration","Orchestration","Airflow 2.x's Pythonic way to define DAGs using decorated functions instead of operator classes.","intermediate",2,"must-know",3,"junior",3,4,"Learn Well — modern Airflow development pattern",["airflow-dags"],["Use @task decorator","Pass data between tasks automatically","Convert classic DAGs to TaskFlow"],"Classic Airflow DAGs require verbose operator instantiation and manual XCom usage. TaskFlow lets you write normal Python functions with @task decorators.","Introduced in Airflow 2.0 to simplify DAG authoring. Reduces boilerplate by 50-70%.","All new Airflow projects should use TaskFlow API. It's the recommended pattern in Airflow 2.x+.","## TaskFlow API\n\n### Classic Style (Verbose)\n```python\nwith DAG('classic_dag', ...) as dag:\n    extract = PythonOperator(\n        task_id='extract',\n        python_callable=extract_fn\n    )\n    transform = PythonOperator(\n        task_id='transform',\n        python_callable=transform_fn\n    )\n    extract >> transform\n```\n\n### TaskFlow Style (Clean)\n```python\n@dag(schedule='@daily', start_date=datetime(2024,1,1))\ndef my_pipeline():\n    @task\n    def extract():\n        return {'data': [1,2,3]}\n    \n    @task\n    def transform(data):\n        return [x * 2 for x in data['data']]\n    \n    raw = extract()\n    transform(raw)  # XCom passed automatically!\n\nmy_pipeline()\n```",R,null,["Rewrite a classic DAG using TaskFlow API"],["airflow-xcom"],["airflow-dags"],["Using classic style for new Airflow 2.x projects"],["What is the TaskFlow API?","How does it handle XCom?","TaskFlow vs classic operators?"],
[{front:"TaskFlow API vs Classic Airflow?",back:"TaskFlow: @task decorator, automatic XCom, Pythonic. Classic: PythonOperator, manual XCom push/pull. TaskFlow is recommended for Airflow 2.x+."}],"TaskFlow API uses @task decorators for clean DAG authoring with automatic XCom. The recommended pattern for Airflow 2.x+."),

T("airflow-xcom","XCom (Cross-Communication)","orchestration","Orchestration","Pass small pieces of data between Airflow tasks — like the output of one task becoming the input of another.","intermediate",1,"must-know",3,"junior",3,4,"Learn Well — fundamental Airflow concept",["airflow-dags"],["Push and pull XCom values","Understand XCom size limits","Use TaskFlow automatic XCom"],"Task A extracts a file path. Task B needs that path to process the file. XCom passes data between them.","Airflow tasks run in separate processes (possibly on different machines). XCom is the mechanism for inter-task communication.","XCom is used in nearly every DAG. TaskFlow API makes it automatic — return values are automatically pushed to XCom.","## XCom\n\n### Manual Push/Pull\n```python\n# Task A: Push\ndef extract(**context):\n    context['ti'].xcom_push(key='file_path', value='/data/file.csv')\n\n# Task B: Pull\ndef transform(**context):\n    path = context['ti'].xcom_pull(task_ids='extract', key='file_path')\n```\n\n### TaskFlow (Automatic)\n```python\n@task\ndef extract():\n    return '/data/file.csv'  # Auto-pushed to XCom\n\n@task\ndef transform(path):  # Auto-pulled from XCom\n    print(path)\n```\n\n### Limitations\n- XCom is stored in the metadata database\n- **Max size ~48KB** (default SQLite) to ~1GB (Postgres)\n- Do NOT pass large DataFrames via XCom\n- For large data: write to S3/GCS, pass the path via XCom",R,null,[],["airflow-pools"],["airflow-dags"],["Passing large DataFrames through XCom (use file paths instead)"],["What is XCom?","XCom size limits?","How do you pass large data between tasks?"],
[{front:"XCom Size Limit?",back:"XCom is stored in the Airflow metadata DB. Keep values small (paths, counts, status). For large data, write to S3/GCS and pass the file path via XCom."}],"XCom passes small data between Airflow tasks. Use for paths, counts, and status — not large datasets. TaskFlow makes XCom automatic."),

T("airflow-prod-best-practices","Airflow Production Best Practices","orchestration","Orchestration","Battle-tested patterns for running Airflow reliably in production at scale.","intermediate",2,"must-know",3,"mid",3,5,"Learn Well — shows production maturity",["airflow-dags","operators","airflow-arch"],["Design idempotent DAGs","Implement proper error handling","Set up monitoring and alerting","Configure resource management"],"Your development DAGs work fine, but in production they fail silently, consume too many resources, and are impossible to debug. Best practices fix this.","Accumulated wisdom from running Airflow at companies like Airbnb (who created it), Lyft, and Spotify.","Senior DEs are expected to know these patterns. They're the difference between a hobby project and a production-grade pipeline.","## Production Best Practices\n\n### 1. Idempotent DAGs\nEvery DAG should produce the same result when re-run.\n```python\n# Bad: INSERT INTO (creates duplicates on retry)\n# Good: MERGE/UPSERT or DELETE+INSERT\n```\n\n### 2. Atomic Tasks\nEach task should either fully succeed or fully fail. No partial state.\n\n### 3. Don't Use Latest, Use Execution Date\n```python\n# Bad: process today's data\n# Good: process {{ ds }} (execution date)\n```\n\n### 4. Set Proper Retries\n```python\ndefault_args = {\n    'retries': 3,\n    'retry_delay': timedelta(minutes=5),\n    'retry_exponential_backoff': True,\n}\n```\n\n### 5. Use SLAs and Alerts\n```python\nsla=timedelta(hours=2)  # Alert if task takes > 2 hours\n```",R,null,["Review an existing DAG and apply 5 best practices"],["kafka-overview"],["airflow-arch"],["Not setting retries on production tasks","Using `start_date=datetime.now()` instead of a fixed date"],["What makes a DAG idempotent?","How do you handle retries?","What is the difference between execution_date and logical_date?"],
[{front:"Key Airflow Production Rules?",back:"1. Idempotent tasks. 2. Atomic operations. 3. Use execution_date, not datetime.now(). 4. Set retries with exponential backoff. 5. SLAs and alerting."}],"Production Airflow requires idempotent tasks, atomic operations, execution_date over now(), proper retries, and SLA alerting."),

// ═══ STREAMING EXPANSION ═══
T("kafka-topics","Kafka Topics & Partitions (Deep Dive)","streaming","Streaming","A Kafka topic is a named stream of records, partitioned for parallelism and replicated for fault tolerance.","intermediate",2,"must-know",4,"junior",4,5,"Learn Deeply — core Kafka architecture concept",["kafka-overview"],["Create and configure topics","Understand partition count impact","Configure replication factor"],"You need to stream 100K events/second. A single queue can't handle this. Kafka topics split the stream across multiple partitions for parallel processing.","Topics + partitions are the core abstraction that makes Kafka horizontally scalable. More partitions = more parallelism.","Production Kafka clusters at companies like LinkedIn handle 7 trillion messages per day across millions of partitions.","## Kafka Topics\n\n### Anatomy\n```\nTopic: orders\n├── Partition 0: [msg1, msg4, msg7...]\n├── Partition 1: [msg2, msg5, msg8...]\n└── Partition 2: [msg3, msg6, msg9...]\n```\n\n### Key Decisions\n| Setting | Recommendation |\n|---------|---------------|\n| Partitions | Start with 6-12 per topic |\n| Replication Factor | 3 for production |\n| Retention | 7 days (or infinite with tiered storage) |\n\n### Partition Key\n```python\nproducer.send('orders', key=b'customer_123', value=order_json)\n```\nMessages with the SAME key always go to the SAME partition. Ensures ordering per customer.",R,null,["Create a topic with 6 partitions and RF=3"],["kafka-producer"],["kafka-overview"],["Setting partition count too low (can't increase easily)","Setting partition count too high (metadata overhead)"],["How does Kafka partition data?","What is a partition key?","How do you choose the number of partitions?"],
[{front:"How does Kafka partitioning work?",back:"Messages are assigned to partitions by hashing the key. Same key → same partition → guaranteed ordering per key. More partitions → more parallelism."}],"Kafka topics are split into partitions for parallelism. Same key → same partition for ordering. Use 6-12 partitions per topic, RF=3 for production."),

T("kafka-producer","Kafka Producer","streaming","Streaming","The client that publishes messages to Kafka topics — with acknowledgment levels, serialization, and batching.","intermediate",2,"must-know",3,"junior",3,5,"Learn Well — essential for building Kafka pipelines",["kafka-topics"],["Configure producer acks levels","Understand serialization","Optimize batching and compression"],"You need to send 50K events/second to Kafka reliably. The producer configuration determines throughput, durability, and latency trade-offs.","Producers are the entry point for all data into Kafka. Their configuration directly impacts data loss risk and throughput.","Every application that sends data to Kafka uses a producer — from microservices logging events to CDC tools like Debezium.","## Kafka Producer\n\n### Acknowledgment Levels (acks)\n| Setting | Durability | Throughput |\n|---------|-----------|------------|\n| acks=0 | No guarantee | Highest |\n| acks=1 | Leader only | Medium |\n| acks=all | All replicas | Lowest (safest) |\n\n### Python Example\n```python\nfrom kafka import KafkaProducer\nimport json\n\nproducer = KafkaProducer(\n    bootstrap_servers='kafka:9092',\n    value_serializer=lambda v: json.dumps(v).encode('utf-8'),\n    acks='all',\n    retries=3\n)\n\nproducer.send('orders', key=b'cust_1', value={'item': 'laptop', 'price': 999})\nproducer.flush()\n```\n\n### Batching\nProducers batch messages before sending to reduce network calls.\n- `batch.size`: Max batch size in bytes (default 16KB)\n- `linger.ms`: Wait time to fill batch (default 0ms)",R,null,["Write a Python producer that sends 1000 messages to a topic"],["kafka-consumer"],["kafka-topics"],["Using acks=0 for critical data (risk of data loss)","Not calling flush() before shutdown"],["What are Kafka acks levels?","acks=0 vs acks=1 vs acks=all?","How does producer batching work?"],
[{front:"Kafka acks=0 vs acks=1 vs acks=all?",back:"acks=0: fire and forget (fastest, may lose data). acks=1: wait for leader ack (balanced). acks=all: wait for all replicas (safest, slowest). Use acks=all for production."}],"Kafka producers send messages with configurable durability (acks). Use acks=all for production. Optimize with batching and compression."),

T("kafka-consumer","Kafka Consumer & Consumer Groups","streaming","Streaming","Consumers read messages from Kafka topics. Consumer groups enable parallel consumption and automatic load balancing.","intermediate",2,"must-know",4,"junior",4,5,"Learn Deeply — fundamental Kafka consumption pattern",["kafka-producer"],["Understand consumer groups","Handle offset commits","Know rebalancing behavior"],"You have a topic with 12 partitions. One consumer can't keep up. Consumer groups let you run 12 consumers in parallel, each reading from a different partition.","Consumer groups are Kafka's killer feature for scalable consumption. They automatically distribute partitions across consumers.","Every Kafka-based system uses consumer groups. They're how you scale consumption horizontally.","## Consumer Groups\n\n### How It Works\n```\nTopic: orders (12 partitions)\nConsumer Group: order-processor\n  Consumer 1 → Partitions 0,1,2,3\n  Consumer 2 → Partitions 4,5,6,7\n  Consumer 3 → Partitions 8,9,10,11\n```\n\n### Key Rules\n1. Each partition is consumed by **exactly one consumer** in a group\n2. A consumer can read from **multiple partitions**\n3. If consumers > partitions, some consumers are **idle**\n4. If a consumer dies, its partitions are **rebalanced** to others\n\n### Offset Commits\n```python\nconsumer = KafkaConsumer(\n    'orders',\n    group_id='order-processor',\n    auto_offset_reset='earliest',\n    enable_auto_commit=True,  # or False for manual\n)\n```\nOffsets track which messages have been consumed. Committed offsets ensure no re-processing after restart.",R,null,["Write a consumer group with 3 consumers and observe partition assignment"],["kafka-schema-registry"],["kafka-producer"],["Having more consumers than partitions (extras sit idle)","Not committing offsets properly (causes re-processing)"],["What is a consumer group?","How are partitions assigned?","What happens when a consumer dies?","What are offsets?"],
[{front:"Kafka Consumer Groups: Key Rule?",back:"Each partition is consumed by exactly 1 consumer in a group. If consumers > partitions, extras are idle. If a consumer fails, its partitions are rebalanced to remaining consumers."}],"Consumer groups distribute partitions across consumers for parallel processing. Each partition → exactly 1 consumer. Auto-rebalance on failure."),

T("kafka-schema-registry","Schema Registry","streaming","Streaming","A centralized schema store that ensures Kafka producers and consumers agree on the data format.","intermediate",1,"good-to-know",2,"mid",2,4,"Know Concept — important for production Kafka",["kafka-consumer"],["Register Avro/JSON schemas","Understand compatibility modes","Use Schema Registry with producers/consumers"],"Producer sends {'name': 'Alice', 'age': 30}. Then changes to {'name': 'Alice', 'years': 30}. Consumer breaks because 'age' is now 'years'. Schema Registry prevents this.","Without schema enforcement, producers can send anything, breaking downstream consumers. Schema Registry is the contract between producers and consumers.","Confluent Schema Registry is the standard. Supports Avro, Protobuf, and JSON Schema.","## Schema Registry\n\n### How It Works\n1. Producer registers schema → gets schema ID\n2. Producer sends message with schema ID prefix\n3. Consumer reads schema ID → fetches schema from registry\n4. Consumer deserializes using the registered schema\n\n### Compatibility Modes\n| Mode | Rule |\n|------|------|\n| BACKWARD | New schema can read old data |\n| FORWARD | Old schema can read new data |\n| FULL | Both backward and forward |\n| NONE | No compatibility check |",R,null,[],["kafka-connect"],["kafka-consumer"],["Not using Schema Registry in production (leads to broken consumers)"],["What is Schema Registry?","BACKWARD vs FORWARD compatibility?"],
[{front:"Schema Registry Compatibility Modes?",back:"BACKWARD: new schema reads old data (safe column addition). FORWARD: old schema reads new data. FULL: both directions. NONE: no enforcement."}],"Schema Registry stores and enforces data schemas for Kafka. Ensures backward/forward compatibility between producers and consumers."),

T("kafka-connect","Kafka Connect & Debezium","streaming","Streaming","Pre-built connectors that move data in and out of Kafka without writing code.","intermediate",2,"must-know",3,"mid",3,5,"Learn Well — the standard for Kafka integrations",["kafka-schema-registry"],["Set up source and sink connectors","Configure Debezium for CDC","Understand connector architecture"],"You need to stream data from Postgres to Kafka to S3. Instead of writing custom producers/consumers, Kafka Connect provides pre-built connectors.","Writing custom Kafka producers for every data source is tedious. Kafka Connect standardizes data integration with 200+ pre-built connectors.","Debezium (CDC connector) and S3 Sink are the most popular connectors. They're used at nearly every company with Kafka.","## Kafka Connect\n\n### Architecture\n```\nSource Systems → Source Connectors → Kafka → Sink Connectors → Target Systems\n```\n\n### Common Connectors\n| Connector | Type | Use Case |\n|-----------|------|----------|\n| Debezium (Postgres) | Source | CDC from databases |\n| S3 Sink | Sink | Write Kafka to S3 |\n| JDBC Source | Source | Poll database tables |\n| Elasticsearch Sink | Sink | Search indexing |\n\n### Debezium CDC\nReads the Postgres WAL and streams every INSERT/UPDATE/DELETE as a Kafka message.\n```json\n{\n  \"op\": \"u\",\n  \"before\": {\"id\": 1, \"name\": \"Alice\", \"city\": \"NYC\"},\n  \"after\":  {\"id\": 1, \"name\": \"Alice\", \"city\": \"SF\"}\n}\n```",R,null,["Set up Debezium with Docker Compose"],["flink"],["kafka-schema-registry"],["Writing custom producers when a connector already exists"],["What is Kafka Connect?","What is Debezium?","Source vs Sink connectors?"],
[{front:"What is Debezium?",back:"An open-source CDC tool that runs as a Kafka Connect source connector. Reads database transaction logs (WAL/Binlog) and streams every change as a Kafka message."}],"Kafka Connect provides pre-built data integration. Debezium is the standard CDC connector. 200+ connectors available for common systems."),

// ═══ AWS EXPANSION ═══
T("aws-glue","AWS Glue","cloud","AWS Cloud","AWS's serverless ETL service — crawlers for schema discovery, Spark-based jobs for transformation, and the Glue Data Catalog.","intermediate",2,"must-know",3,"junior",3,4,"Learn Well — the default ETL service on AWS",["s3","spark-dataframes"],["Set up Glue crawlers","Write Glue ETL jobs","Use the Glue Data Catalog"],"You have raw data in S3 and need to transform it without managing any infrastructure. Glue provides serverless Spark + automatic schema discovery.","AWS created Glue to compete with Databricks as a managed Spark service. It also serves as the default data catalog for AWS analytics services.","Glue Crawlers scan S3 and auto-detect schemas. Glue Jobs run PySpark transformations. Athena queries use the Glue Catalog.","## AWS Glue\n\n### Components\n1. **Crawlers**: Scan data in S3, detect schema, populate the Data Catalog\n2. **Data Catalog**: Central metadata store (tables, schemas, partitions)\n3. **ETL Jobs**: Serverless PySpark/Python Shell jobs\n4. **Glue Studio**: Visual ETL designer\n\n### Glue vs Databricks vs EMR\n| Feature | Glue | Databricks | EMR |\n|---------|------|-----------|-----|\n| Management | Serverless | Managed | Semi-managed |\n| Cost | Pay per DPU-hour | Pay per DBU | Pay per instance-hour |\n| Best for | Simple ETL | Complex analytics | Custom Spark |",R,null,["Create a Glue Crawler and ETL job"],["aws-athena"],["s3"],["Using Glue for complex analytics (use Databricks or EMR instead)"],["What is AWS Glue?","Glue vs Databricks?","What is the Glue Data Catalog?"],
[{front:"AWS Glue Components?",back:"1. Crawlers: auto-detect schemas. 2. Data Catalog: central metadata store. 3. ETL Jobs: serverless PySpark. 4. Glue Studio: visual ETL designer."}],"AWS Glue provides serverless ETL (Spark), schema discovery (Crawlers), and metadata management (Data Catalog). Default ETL service on AWS."),

T("aws-athena","Amazon Athena","cloud","AWS Cloud","Query S3 data directly using SQL — no infrastructure to manage, pay per query.","beginner",1,"must-know",3,"junior",3,4,"Learn Well — the easiest way to query S3 data",["s3","aws-glue"],["Write Athena queries","Optimize with partitioning and Parquet","Understand pricing model"],"You have 10TB of CSV files in S3. You want to run SQL queries without setting up a data warehouse. Athena lets you query S3 directly.","AWS created Athena (based on Presto) for ad-hoc querying of S3 data. It's the simplest way to query a data lake.","Athena is used for ad-hoc exploration and lightweight analytics. For heavy workloads, use Redshift or Databricks.","## Amazon Athena\n\n### How It Works\n1. Data lives in S3 (Parquet, CSV, JSON, ORC)\n2. Glue Crawler creates table definitions in the Glue Catalog\n3. Athena queries the data using standard SQL\n4. Pay $5 per TB scanned\n\n### Cost Optimization\n- Use **Parquet/ORC** instead of CSV (columnar = scan less data)\n- **Partition** data by date/region (only scan relevant partitions)\n- **CTAS** (CREATE TABLE AS SELECT) to convert CSV to Parquet\n\n### Example\n```sql\nSELECT date, SUM(revenue) \nFROM orders \nWHERE date = '2024-01-01'  -- Partition pruning!\nGROUP BY date\n```",R,null,["Query a partitioned Parquet dataset in Athena"],["aws-lambda"],["aws-glue"],["Querying CSV files in Athena (use Parquet for 90% cost reduction)"],["What is Athena?","How do you optimize Athena costs?","Athena vs Redshift?"],
[{front:"Athena Cost Optimization?",back:"1. Use Parquet/ORC (columnar). 2. Partition data. 3. Use CTAS to convert CSV to Parquet. Pricing: $5/TB scanned. Parquet can reduce costs by 90%."}],"Athena queries S3 data using SQL. $5/TB scanned. Optimize with Parquet format and data partitioning for 90% cost reduction."),

T("aws-lambda","AWS Lambda (Overview)","cloud","AWS Cloud","Run code without managing servers — triggered by events like S3 uploads, API calls, or schedules.","beginner",1,"good-to-know",2,"junior",2,3,"Know Concept — useful for lightweight pipeline triggers",["aws-iam"],["Understand Lambda functions","Know common triggers (S3, API Gateway, EventBridge)","Understand limitations (15 min timeout, 10GB memory)"],"A new file lands in S3. You want to automatically trigger a Glue job. Lambda acts as the event-driven 'glue' between AWS services.","Lambda enables event-driven architectures without managing servers. For DEs, it's primarily used as a lightweight trigger/orchestrator.","DEs use Lambda for: triggering Glue jobs on S3 events, lightweight API endpoints, small data transformations (< 15 min).","## AWS Lambda\n\n### Key Properties\n- **Serverless**: No infrastructure to manage\n- **Event-driven**: Triggered by S3, API Gateway, EventBridge\n- **Limits**: 15 min timeout, 10GB memory, 250MB deployment package\n\n### Common DE Use Cases\n1. Trigger Glue/EMR job when file lands in S3\n2. Transform small payloads (API → S3)\n3. Dead letter queue processing\n4. Scheduled health checks\n\n### NOT For\n- Long-running ETL (> 15 min)\n- Large data processing (use Spark/Glue instead)",R,null,[],["aws-emr"],["aws-iam"],["Using Lambda for large ETL jobs (15 min timeout)"],["What is AWS Lambda?","Lambda vs Glue for ETL?","What are Lambda's limitations?"],
[{front:"AWS Lambda Limits?",back:"15 minute max timeout. 10GB max memory. 250MB deployment package. Not suitable for heavy ETL — use Glue/EMR/Spark instead."}],"Lambda runs serverless functions triggered by events. Use for lightweight triggers (S3 → Glue). Not for heavy ETL (15 min limit)."),

T("aws-emr","Amazon EMR","cloud","AWS Cloud","Managed Hadoop/Spark clusters on AWS — more control than Glue, more setup required.","intermediate",1,"good-to-know",2,"mid",2,3,"Know Concept — alternative to Glue/Databricks on AWS",["spark-dataframes","ec2"],["Understand EMR cluster types","Compare EMR vs Glue vs Databricks","Know when to choose EMR"],"You need full control over your Spark configuration, custom libraries, and long-running interactive sessions. EMR gives you a managed Spark cluster without the Databricks price tag.","EMR predates Glue and Databricks. It's a semi-managed approach — you get control over the Spark cluster but must handle more configuration.","EMR is chosen when Glue is too limited (custom JARs, GPU instances) and Databricks is too expensive.","## Amazon EMR\n\n### EMR vs Glue vs Databricks\n| Feature | EMR | Glue | Databricks |\n|---------|-----|------|------------|\n| Control | Full | Limited | Medium |\n| Setup | More | Serverless | Managed |\n| Cost | Lower | Medium | Higher |\n| Best for | Custom Spark | Simple ETL | Full analytics |",R,null,[],["redshift"],["ec2"],["Over-engineering with EMR when Glue would suffice"],["EMR vs Glue vs Databricks?","When would you choose EMR?"],
[{front:"EMR vs Glue?",back:"EMR: full Spark control, more setup, cheaper. Glue: serverless, limited config, easier. Choose EMR for custom Spark requirements; Glue for simple ETL."}],"EMR provides managed Spark clusters with full control. Choose over Glue when you need custom configuration; choose Databricks for full analytics."),

// ═══ DEVOPS EXPANSION ═══
T("docker-compose","Docker Compose","devops","DevOps & CI/CD","Define and run multi-container applications — your entire development stack in one YAML file.","beginner",2,"must-know",3,"junior",3,4,"Learn Well — used in every DE project",["docker"],["Write docker-compose.yml","Configure multi-service environments","Manage volumes and networks"],"Your project needs Postgres, Kafka, Airflow, and Redis. Instead of installing each separately, Docker Compose starts everything with one command.","Docker runs single containers. Compose orchestrates multiple containers as a single application — essential for local DE development.","Every DE project has a docker-compose.yml for local development: Postgres + Airflow + Kafka + Spark in one file.","## Docker Compose\n\n### Example\n```yaml\nversion: '3.8'\nservices:\n  postgres:\n    image: postgres:15\n    environment:\n      POSTGRES_DB: analytics\n      POSTGRES_PASSWORD: secret\n    ports:\n      - '5432:5432'\n    volumes:\n      - pgdata:/var/lib/postgresql/data\n  \n  airflow:\n    image: apache/airflow:2.8.0\n    depends_on:\n      - postgres\n    ports:\n      - '8080:8080'\n\nvolumes:\n  pgdata:\n```\n\n### Commands\n```bash\ndocker-compose up -d      # Start all services\ndocker-compose down        # Stop all services\ndocker-compose logs -f     # Follow logs\ndocker-compose ps          # List running services\n```",R,null,["Create a docker-compose.yml with Postgres + Airflow"],["ci-cd"],["docker"],["Not using volumes (data lost when container stops)"],["What is Docker Compose?","Docker vs Docker Compose?"],
[{front:"Docker vs Docker Compose?",back:"Docker: runs single containers. Compose: orchestrates multiple containers from a YAML file. Use Compose for local dev environments (Postgres + Kafka + Airflow)."}],"Docker Compose orchestrates multi-container environments from YAML. Essential for local DE development with Postgres, Kafka, Airflow."),

// ═══ PROJECTS EXPANSION ═══
T("project-python-etl","Project: Python ETL Pipeline","projects","Projects","Build a complete ETL pipeline using Python, Pandas, and PostgreSQL — your first portfolio project.","beginner",8,"must-know",3,"foundation",3,4,"Learn Deeply — demonstrates foundational skills",["python","sql"],["Extract data from APIs and CSVs","Transform with Pandas","Load into PostgreSQL","Schedule with cron/Airflow"],"Your first real project. Extract data from a public API, clean and transform it with Pandas, and load it into a Postgres database.","Portfolio projects are the #1 way to get hired as a Data Engineer without prior experience. This project proves you can build end-to-end pipelines.","This project pattern (API → Transform → Database) is used in every company for data ingestion.",
"## Project: Python ETL\n\n### Architecture\n```\nPublic API → Python Script → Pandas Transform → PostgreSQL\n```\n\n### Steps\n1. Extract: Fetch data from a public API (e.g., OpenWeather, Spotify, GitHub)\n2. Transform: Clean, deduplicate, type-cast with Pandas\n3. Load: Insert into PostgreSQL using SQLAlchemy\n4. Orchestrate: Schedule with cron or Airflow\n\n### Requirements\n- Error handling and logging\n- Idempotent loads (upsert)\n- Configuration via environment variables\n- README with architecture diagram",R,{title:"Weather Data Pipeline",description:"Extract weather data from OpenWeatherMap API, transform with Pandas, and load into PostgreSQL with daily scheduling.",skills:["Python","Pandas","PostgreSQL","REST APIs"],estimatedHours:8},["Build the full pipeline"],["project-spark-analytics"],["python"],["No error handling","Hardcoded credentials"],["Walk me through a project you've built."],
[{front:"What makes a good portfolio project?",back:"End-to-end (Extract → Transform → Load), error handling, idempotent loads, environment variables for config, documentation with architecture diagram."}],"Build a complete Python ETL pipeline: API → Pandas → PostgreSQL. First portfolio project demonstrating foundational DE skills."),

T("project-spark-analytics","Project: Spark Analytics Pipeline","projects","Projects","Process a large dataset (millions of rows) using PySpark — window functions, aggregations, and Delta Lake.","intermediate",10,"must-know",4,"junior",4,5,"Learn Deeply — demonstrates Spark proficiency",["spark-dataframes","spark-window-functions","delta-format"],["Process millions of rows with PySpark","Use window functions for analytics","Write to Delta Lake with partitioning","Optimize with caching and broadcast joins"],"Your second project proves you can handle big data. Process a 10M+ row dataset with Spark, write optimized Delta tables, and produce analytical outputs.","This project proves you're not just a Python developer — you can work with distributed data processing at scale.","This is the type of work a Junior-Mid DE does daily at companies using Spark/Databricks.",
"## Project: Spark Analytics\n\n### Architecture\n```\nCSV/Parquet (10M+ rows) → PySpark → Delta Lake → Analytics Views\n```\n\n### Requirements\n1. Use a large public dataset (NYC Taxi, Stack Overflow, IMDb)\n2. Implement: window functions, joins, aggregations\n3. Write partitioned Delta tables\n4. Create summary views with business metrics\n5. Optimize: broadcast joins, repartition, caching",R,{title:"NYC Taxi Trip Analytics",description:"Analyze 10M+ NYC taxi trips: fare trends, driver patterns, zone analytics. Write optimized Delta tables with medallion architecture.",skills:["PySpark","Delta Lake","Window Functions","Performance Tuning"],estimatedHours:10},["Build the full Spark analytics pipeline"],["project-airflow-pipeline"],["spark-dataframes"],["Processing data without checking data quality first"],["What Spark optimizations did you use?"],
[{front:"Spark Analytics Project Checklist?",back:"1. Large dataset (10M+ rows). 2. Window functions + aggregations. 3. Delta Lake partitioned writes. 4. Performance tuning (broadcast, cache, repartition). 5. README."}],"Build a PySpark analytics pipeline on a 10M+ row dataset. Demonstrates Spark proficiency with window functions, Delta Lake, and performance tuning."),

T("project-e2e","Project: Production-Grade End-to-End Pipeline","projects","Projects","The capstone project: ingest, transform, model, orchestrate, test, monitor, and deploy a complete data platform.","advanced",20,"must-know",5,"mid",5,5,"Learn Deeply — the ultimate portfolio piece",["project-spark-analytics","dbt-best-practices","airflow-prod-best-practices","docker-compose"],["Build a complete lakehouse pipeline","Implement medallion architecture","Orchestrate with Airflow","Test with dbt and Great Expectations","Deploy with Docker and CI/CD"],"This is the project that gets you hired. A production-grade pipeline that demonstrates every skill a mid-level DE needs.","This project is the culmination of the entire DEOS curriculum. It proves you can build and operate real data infrastructure.","This mirrors what a real DE team builds: ingestion → lakehouse → transformation → serving → monitoring.",
"## Capstone: Production Pipeline\n\n### Architecture\n```\nData Sources → Ingestion → Bronze (raw) → Silver (clean) → Gold (business) → Dashboard\n     ↓              ↓           ↓              ↓             ↓\n   CDC/API      Kafka/API    Delta Lake    dbt Models    Metabase/Superset\n                    ↓\n              Airflow (orchestration)\n                    ↓\n              Docker + CI/CD (deployment)\n```\n\n### Requirements\n1. Multiple data sources (API + database + files)\n2. Medallion architecture (Bronze/Silver/Gold)\n3. dbt models with tests and documentation\n4. Airflow DAGs for orchestration\n5. Docker Compose for local development\n6. CI/CD pipeline (GitHub Actions)\n7. Data quality checks\n8. README with architecture diagram, setup instructions, and design decisions",R,{title:"E-Commerce Data Platform",description:"Complete lakehouse platform: ingest orders + products from API and Postgres, build medallion architecture with Spark, transform with dbt, orchestrate with Airflow, deploy with Docker.",skills:["Spark","dbt","Airflow","Docker","Delta Lake","PostgreSQL","CI/CD"],estimatedHours:20},["Build the complete platform"],["sys-design-intro"],["project-spark-analytics"],["Skipping tests and documentation"],["Walk me through your end-to-end project."],
[{front:"Production Pipeline Components?",back:"Ingestion → Bronze → Silver → Gold (medallion). Orchestration: Airflow. Transformation: dbt. Storage: Delta Lake. Deployment: Docker + CI/CD. Testing: Great Expectations."}],"Capstone project: complete lakehouse with medallion architecture, dbt, Airflow, Docker, and CI/CD. The ultimate portfolio piece for mid-level DE roles."),

// ═══ SYSTEM DESIGN EXPANSION ═══
T("sys-design-capacity","System Design: Capacity Planning","system-design","System Design","Estimate storage, compute, and throughput requirements before designing a data system.","advanced",2,"must-know",4,"mid",4,4,"Learn Deeply — first step in every system design interview",["sys-design-intro"],["Estimate data volume and growth","Calculate storage requirements","Determine throughput needs"],"Interviewer: 'Design a pipeline for Uber's ride data.' First question: 'How many rides per day? How large is each event? How many days of retention?' Without capacity planning, your design is baseless.","Capacity planning is the FIRST step in every system design interview. It determines whether you need Kafka or a simple queue, S3 or a database.","Every system design discussion starts with back-of-the-envelope calculations.","## Capacity Planning\n\n### Step 1: Estimate Volume\n- Events per day: 10M rides × 1KB each = **10 GB/day**\n- Monthly: 300 GB/month\n- Yearly: 3.6 TB/year\n- With replication (3x): **10.8 TB/year**\n\n### Step 2: Throughput\n- 10M events / 86,400 seconds = **~115 events/second** (average)\n- Peak (2x): ~230 events/second\n- Can a single Postgres handle this? Yes. Do we need Kafka? Probably not at this scale.\n\n### Step 3: Storage Decisions\n| Volume | Storage Choice |\n|--------|---------------|\n| < 100 GB | Postgres/MySQL |\n| 100 GB - 10 TB | S3 + Parquet |\n| > 10 TB | S3 + Delta Lake + Spark |",R,null,["Do capacity planning for 3 different scenarios"],["sys-design-batch"],["sys-design-intro"],["Skipping capacity planning and jumping to architecture"],["How do you estimate storage for 100M events/day?"],
[{front:"Capacity Planning Steps?",back:"1. Estimate events/day × event size = daily volume. 2. Calculate throughput (events/second). 3. Factor in replication and retention. 4. Choose appropriate storage tier."}],"Capacity planning estimates volume, throughput, and storage before designing. First step in every system design interview."),

T("sys-design-batch","System Design: Batch Pipeline","system-design","System Design","Design a batch processing pipeline from data ingestion to serving layer.","advanced",2,"must-know",4,"mid",4,5,"Learn Deeply — most common system design question for DEs",["sys-design-capacity"],["Design end-to-end batch architecture","Choose appropriate tools for each layer","Handle failures and retries"],"Design a daily batch pipeline that processes 100GB of transaction data, transforms it, and serves it to dashboards.","Batch pipeline design is the most frequently asked system design question in DE interviews.","This is what most data teams build: daily/hourly batch pipelines from source systems to analytics.","## Batch Pipeline Design\n\n### Generic Architecture\n```\nSources → Ingestion → Raw Storage → Processing → Serving → Consumers\n  ↓           ↓            ↓            ↓           ↓          ↓\nDBs/APIs  Airbyte/Glue   S3 Bronze   Spark/dbt   Warehouse  Dashboards\n```\n\n### Key Decisions\n1. **Ingestion**: Airbyte (open source) vs Fivetran (managed)\n2. **Storage**: S3 + Parquet/Delta (cost-effective) vs Snowflake (managed)\n3. **Processing**: Spark (heavy) vs dbt (SQL-based)\n4. **Orchestration**: Airflow (standard) vs Dagster (modern)\n5. **Serving**: Redshift/Snowflake for BI, Delta/Iceberg for lakehouse",R,null,["Design a batch pipeline for an e-commerce company"],["sys-design-streaming"],["sys-design-capacity"],["Not discussing failure handling and retries"],["Design a batch pipeline for processing daily sales data."],
[{front:"Batch Pipeline Components?",back:"Sources → Ingestion (Airbyte) → Raw Storage (S3) → Processing (Spark/dbt) → Serving (Warehouse) → Consumers (Dashboards). Orchestrated by Airflow."}],"Batch pipeline design: sources → ingestion → storage → processing → serving. Most common DE system design question."),

T("sys-design-streaming","System Design: Streaming Pipeline","system-design","System Design","Design a real-time data processing system using Kafka, Flink/Spark Streaming, and a serving layer.","advanced",2,"must-know",4,"senior",4,4,"Learn Deeply — increasingly common in interviews",["sys-design-batch","kafka-overview"],["Design streaming architecture","Handle late data and ordering","Choose streaming vs micro-batch"],"Design a real-time fraud detection system that processes credit card transactions within 500ms.","Streaming interviews test whether you understand the unique challenges: ordering, late data, exactly-once, and state management.","Companies like Uber, Stripe, and Netflix use streaming pipelines for real-time analytics and fraud detection.","## Streaming Pipeline Design\n\n### Architecture\n```\nEvents → Message Queue → Stream Processor → Serving → Actions\n  ↓           ↓               ↓               ↓          ↓\nApp logs   Kafka           Flink/Spark      Redis/DB   Alerts/Dashboard\n```\n\n### Key Challenges\n1. **Ordering**: Events may arrive out of order\n2. **Late Data**: Events may arrive after the processing window closes\n3. **Exactly-Once**: Avoiding duplicate processing\n4. **State**: Managing aggregation state across failures\n5. **Backpressure**: Handling burst traffic",R,null,["Design a streaming pipeline for click analytics"],["sys-design-netflix"],["sys-design-batch"],["Not discussing late data handling"],["Design a real-time analytics pipeline."],
[{front:"Streaming Pipeline Challenges?",back:"1. Out-of-order events. 2. Late data (watermarks). 3. Exactly-once semantics. 4. State management. 5. Backpressure handling."}],"Streaming pipeline design: Kafka → Flink/Spark → Serving. Key challenges: ordering, late data, exactly-once, state, backpressure."),

// ═══ INTERVIEW PREP EXPANSION ═══
T("interview-spark","Spark Interview Prep","interview","Interview Preparation","Top 30 Apache Spark interview questions with detailed answers — from basic concepts to performance tuning.","intermediate",3,"must-know",5,"junior",5,5,"Learn Deeply — Spark is the most tested DE skill",["spark-tuning","aqe","spark-window-functions"],["Answer the top 30 Spark interview questions","Explain internal architecture","Debug performance problems verbally"],"Spark questions appear in 90% of DE interviews. This module covers every commonly asked question with production-quality answers.","Spark is the core skill tested in DE interviews. Knowing Spark deeply is the fastest path to getting hired.","These questions are asked at Amazon, Microsoft, Databricks, Uber, Airbnb, and every Spark-using company.","## Top Spark Interview Questions\n\n### Architecture\n1. Explain Spark's architecture (Driver, Executors, Cluster Manager)\n2. What is lazy evaluation?\n3. Transformations vs Actions?\n4. What is the DAG?\n5. Catalyst Optimizer?\n\n### DataFrames\n6. DataFrame vs Dataset vs RDD?\n7. How do Window Functions work?\n8. Explain broadcast joins\n9. repartition vs coalesce?\n\n### Performance\n10. How do you identify data skew?\n11. What is AQE?\n12. How do you tune shuffle partitions?\n13. Caching vs Persistence?\n14. What causes OOM errors in Spark?\n\n### Advanced\n15. How does Structured Streaming work?\n16. What is Tungsten?\n17. How does Spark achieve fault tolerance?",R,null,["Practice answering each question in 2-3 minutes"],["interview-kafka"],["spark-tuning"],["Giving superficial answers without explaining WHY"],["All questions in the theory section above"],
[{front:"Top 3 Spark Interview Topics?",back:"1. Architecture (DAG, Catalyst, lazy evaluation). 2. Performance (skew, AQE, shuffle partitions, broadcast). 3. DataFrames (window functions, joins, repartition vs coalesce)."}],"Comprehensive Spark interview prep covering architecture, DataFrames, performance tuning, and advanced topics."),

T("interview-resume","Resume Building for DEs","interview","Interview Preparation","Craft a resume that gets past ATS filters and impresses hiring managers at top tech companies.","beginner",2,"must-know",4,"foundation",4,1,"Learn Deeply — your resume is the gateway to interviews",["project-e2e"],["Write impact-driven bullet points","Structure a 1-page technical resume","Highlight projects effectively","Pass ATS filters"],"You have the skills but your resume doesn't show it. This module teaches you to write a resume that gets callbacks from Amazon, Microsoft, and Databricks.","Most qualified candidates get rejected because their resume doesn't clearly communicate their skills. Resume optimization is a critical skill.","Recruiters spend 6-10 seconds on initial resume screening. Your resume must pass the '6-second test'.","## DE Resume Guide\n\n### Structure\n1. **Header**: Name, LinkedIn, GitHub, Portfolio\n2. **Summary**: 2 lines — your DE identity\n3. **Skills**: Tools you've used (Spark, Airflow, dbt, Kafka, AWS, SQL, Python)\n4. **Experience/Projects**: 3-5 entries with impact metrics\n5. **Education**: Brief\n\n### Bullet Point Formula\n```\n[Action Verb] + [What You Built] + [Technology Used] + [Measurable Impact]\n```\nExample:\n\"Built a Delta Lake pipeline using PySpark that processed 50M daily events, reducing dashboard latency from 4 hours to 15 minutes.\"\n\n### Common Mistakes\n- Listing tools without context\n- No measurable impact\n- Too many pages (keep to 1)\n- Generic summary",R,null,["Write 5 impact-driven bullet points for your projects"],["interview-mock"],["project-e2e"],["Listing technologies without showing impact","Making the resume longer than 1 page"],["Walk me through your resume."],
[{front:"DE Resume Bullet Formula?",back:"[Action Verb] + [What You Built] + [Tech Used] + [Impact]. Example: Built a Delta Lake pipeline (PySpark) processing 50M events/day, reducing latency from 4hrs to 15min."}],"Write impact-driven resumes: Action + Built What + Technology + Measurable Impact. Keep to 1 page. Highlight projects with metrics."),

T("interview-mock","Mock Interviews & Strategy","interview","Interview Preparation","Prepare for the full DE interview loop: screening, technical, system design, and behavioral rounds.","intermediate",3,"must-know",5,"junior",5,1,"Learn Deeply — practice is the only way to get comfortable",["interview-spark","interview-resume","behavioral-interview"],["Understand the DE interview loop","Practice the STAR method","Time-box system design answers","Handle 'I don't know' gracefully"],"You know Spark, SQL, and Airflow — but you freeze in interviews. This module teaches the META-SKILL of interviewing: pacing, structure, and communication.","Technical knowledge is necessary but not sufficient. Interview performance depends on communication, structure, and practice.","Top performers practice mock interviews 5-10 times before real interviews. The pattern: explain your thought process, not just the answer.","## DE Interview Loop\n\n### Typical Rounds\n1. **Recruiter Screen** (30 min): Behavioral, motivation, salary\n2. **Technical Screen** (60 min): SQL + Python coding\n3. **System Design** (60 min): Design a data pipeline\n4. **Deep Dive** (60 min): Spark/Kafka/Airflow deep technical\n5. **Behavioral** (45 min): STAR method stories\n\n### System Design Framework (45 min)\n1. **Clarify** (5 min): Ask questions about requirements\n2. **Estimate** (5 min): Back-of-envelope calculations\n3. **Design** (20 min): Draw architecture, explain trade-offs\n4. **Deep Dive** (10 min): Discuss failure modes, scaling\n5. **Wrap Up** (5 min): Summarize, discuss monitoring\n\n### When You Don't Know\n\"I haven't worked with that specifically, but based on my experience with [similar thing], I would approach it by...\"",R,null,["Practice a 45-minute system design with a friend or recording"],[""],["interview-spark"],["Not practicing out loud (thinking ≠ speaking)","Jumping to solution without clarifying requirements"],["How do you prepare for a DE interview?"],
[{front:"System Design Interview Framework?",back:"1. Clarify requirements (5 min). 2. Capacity estimation (5 min). 3. High-level design (20 min). 4. Deep dive (10 min). 5. Wrap up (5 min)."}],"Practice the full interview loop: technical screen, system design, deep dive, behavioral. Use frameworks for structured answers.")
];

filtered.push(...newModules);
fs.writeFileSync('src/data/modules.json', JSON.stringify(filtered, null, 2));
console.log('B9-B15 (Airflow+Stream+AWS+DevOps+Projects+SysDesign+Interview): Added ' + newModules.length + ' modules. Total: ' + filtered.length);
