const fs = require('fs');
const existingModules = JSON.parse(fs.readFileSync('src/data/modules.json', 'utf8'));

// Remove any existing modules with these IDs to avoid duplicates
const newIds = ['idempotency','schema-evolution','data-lineage','data-observability','cdc','data-contracts-v2',
  'lambda-arch','kappa-arch','data-catalog',
  'xml','orc','bucketing','small-file','partitioning-storage','delta-format-v2','iceberg-v2','hudi-v2',
  'replication','fault-tolerance','cap-theorem','consistency-models','data-locality'];
const filtered = existingModules.filter(m => !newIds.includes(m.id));

const newModules = [
// ═══ CONCEPTS EXPANSION ═══
{
  id:"idempotency",title:"Idempotency in Data Pipelines",phase:"concepts",phaseLabel:"Modern DE Concepts",
  description:"Understand why running a pipeline twice should produce the same result — and how to design for it.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:4,
  careerLevel:"junior",interviewImportance:4,productionImportance:5,
  interviewRecommendation:"Learn Deeply — asked in every system design interview",
  prerequisites:["data-pipeline"],
  learningObjectives:["Define idempotency","Design idempotent writes using MERGE/UPSERT","Understand exactly-once vs at-least-once semantics"],
  problemItSolves:"If your Airflow DAG fails halfway and retries, it might insert the same 1M rows twice. Without idempotency, your data warehouse has duplicates and your reports are wrong.",
  whyItExists:"Failures are inevitable in distributed systems. Networks drop, servers crash, jobs timeout. Idempotency ensures that retrying a failed job does not corrupt data.",
  realWorldUsage:"Every production pipeline at Netflix, Uber, and Spotify uses idempotent writes. The standard pattern is MERGE (upsert) instead of INSERT.",
  theory:"## Idempotency\n\n### Definition\nAn operation is **idempotent** if running it once produces the same result as running it N times.\n\n### Why It Matters\n```\nRun 1: INSERT 1000 rows → Table has 1000 rows ✓\nRun 2: INSERT 1000 rows → Table has 2000 rows ✗ (DUPLICATES!)\n```\n\n### How to Achieve It\n1. **MERGE/UPSERT**: Instead of INSERT, use `MERGE INTO target USING source ON key WHEN MATCHED THEN UPDATE WHEN NOT MATCHED THEN INSERT`.\n2. **Delete-then-Insert**: Delete the partition first, then insert. `DELETE FROM table WHERE date = '2024-01-01'; INSERT INTO table SELECT * FROM staging WHERE date = '2024-01-01';`\n3. **Overwrite Partition**: In Spark: `df.write.mode('overwrite').partitionBy('date').saveAsTable(...)` overwrites only the affected partition.\n\n### Exactly-Once vs At-Least-Once\n- **At-Least-Once**: The message/event is processed at least once (may have duplicates). Kafka default.\n- **Exactly-Once**: The message is processed exactly once. Requires idempotent consumers + transactional writes.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Rewrite an INSERT-based pipeline to use MERGE"],
  nextTopics:["schema-evolution"],previousTopics:["data-pipeline"],
  commonMistakes:["Using INSERT instead of MERGE in retry-able pipelines","Assuming cloud services guarantee exactly-once delivery (most don't)"],
  interviewQuestions:["What is idempotency?","How do you make a Spark write idempotent?","What is the difference between exactly-once and at-least-once?"],
  flashcards:[{front:"What does idempotent mean?",back:"An operation that produces the same result whether executed once or multiple times. Example: MERGE is idempotent, INSERT is not."}],
  summary:"Idempotency ensures running a pipeline multiple times produces the same result. Achieve it using MERGE/UPSERT or partition-level overwrites."
},
{
  id:"schema-evolution",title:"Schema Evolution",phase:"concepts",phaseLabel:"Modern DE Concepts",
  description:"Learn how to safely change your data schema (add/remove/rename columns) without breaking downstream consumers.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:3,
  careerLevel:"junior",interviewImportance:3,productionImportance:5,
  interviewRecommendation:"Learn Well — critical for production lakehouse work",
  prerequisites:["data-pipeline","parquet"],
  learningObjectives:["Understand backward and forward compatibility","Handle schema changes in Parquet/Avro","Use Delta Lake schema evolution features"],
  problemItSolves:"Your upstream team adds a new column to their API response. If your pipeline is rigid, it crashes. If your storage format doesn't support evolution, you have to rewrite all historical data.",
  whyItExists:"Business requirements change constantly. Schemas must evolve without requiring expensive full-table rewrites or breaking dashboards.",
  realWorldUsage:"Delta Lake's `mergeSchema` option lets Spark automatically add new columns to existing tables. Avro's schema registry ensures producers and consumers agree on the schema.",
  theory:"## Schema Evolution\n\n### Compatibility Types\n- **Backward Compatible**: New schema can read OLD data. (Adding a column with a default value).\n- **Forward Compatible**: Old schema can read NEW data. (Adding an optional column).\n- **Full Compatible**: Both backward and forward. The gold standard.\n\n### Breaking Changes\n- Removing a required column.\n- Changing a column's data type (e.g., INT → STRING).\n- Renaming a column (old code still references the old name).\n\n### Delta Lake Schema Evolution\n```python\ndf.write.format('delta') \\\n  .option('mergeSchema', 'true') \\\n  .mode('append') \\\n  .save('/data/table')\n```\nThis automatically adds any new columns in the DataFrame to the Delta table.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Add a new column to a Delta table using mergeSchema"],
  nextTopics:["data-lineage"],previousTopics:["idempotency"],
  commonMistakes:["Removing columns without checking downstream dependencies","Not using a schema registry with Kafka/Avro"],
  interviewQuestions:["What is schema evolution?","Backward vs forward compatibility?","How does Delta Lake handle schema changes?"],
  flashcards:[{front:"Backward vs Forward Compatibility?",back:"Backward: New code reads old data. Forward: Old code reads new data. Full: Both directions work."}],
  summary:"Schema evolution allows safe column additions/modifications without breaking pipelines. Use Delta Lake mergeSchema or Avro Schema Registry."
},
{
  id:"data-lineage",title:"Data Lineage",phase:"concepts",phaseLabel:"Modern DE Concepts",
  description:"Track where data comes from, how it transforms, and where it ends up.",
  difficulty:"intermediate",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"mid",interviewImportance:2,productionImportance:4,
  interviewRecommendation:"Know Concept — important for governance discussions",
  prerequisites:["data-pipeline","data-governance"],
  learningObjectives:["Define data lineage","Understand column-level vs table-level lineage","Know tools like OpenLineage, DataHub, Atlan"],
  problemItSolves:"A dashboard number looks wrong. Without lineage, you spend hours manually tracing which tables feed into it. With lineage, you click a button and see the full chain: Source API → Bronze → Silver → Gold → Dashboard.",
  whyItExists:"Regulatory compliance (GDPR: 'show me where this user's PII lives') and debugging both require knowing the full data journey.",
  realWorldUsage:"Companies like Airbnb use DataHub. Databricks Unity Catalog has built-in lineage. OpenLineage is the open-source standard.",
  theory:"## Data Lineage\n\n### What Is It?\nA visual or queryable map of data flow:\n```\nPostgres (source) → Airbyte → S3 Bronze → Spark → S3 Silver → dbt → Snowflake Gold → Tableau Dashboard\n```\n\n### Types\n- **Table-Level**: Which tables feed into which tables.\n- **Column-Level**: Which specific columns are derived from which source columns.\n\n### Tools\n| Tool | Type | Notes |\n|------|------|-------|\n| OpenLineage | Open Source Standard | Integrates with Airflow, Spark |\n| DataHub | Open Source Platform | LinkedIn's metadata platform |\n| Atlan | Commercial | Modern data catalog |\n| Unity Catalog | Databricks | Built into Databricks |",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["data-observability"],previousTopics:["data-governance"],
  commonMistakes:["Only tracking table-level lineage (column-level is much more useful for debugging)"],
  interviewQuestions:["What is data lineage?","Table-level vs column-level lineage?","Name a lineage tool."],
  flashcards:[{front:"What is Data Lineage?",back:"A map showing where data comes from, how it's transformed, and where it goes. Enables impact analysis, debugging, and compliance."}],
  summary:"Data lineage tracks the complete journey of data from source to consumption. Critical for debugging, compliance, and impact analysis."
},
{
  id:"data-observability",title:"Data Observability",phase:"concepts",phaseLabel:"Modern DE Concepts",
  description:"Monitor the health of your data pipelines: freshness, volume, schema, distribution, and lineage.",
  difficulty:"intermediate",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"mid",interviewImportance:2,productionImportance:4,
  interviewRecommendation:"Know Concept — increasingly asked in mid/senior interviews",
  prerequisites:["data-quality","data-lineage"],
  learningObjectives:["Define the 5 pillars of data observability","Understand proactive vs reactive monitoring","Know tools like Monte Carlo, Great Expectations, Elementary"],
  problemItSolves:"Your pipeline ran successfully (Airflow shows green), but the data inside is wrong — 90% of records have NULL revenue. Without observability, no one notices until the CFO sees a broken report.",
  whyItExists:"Pipeline success ≠ data correctness. You need to monitor the DATA itself, not just the pipeline infrastructure.",
  realWorldUsage:"Companies use Monte Carlo or Elementary to set up automated anomaly detection on data freshness, volume, and distributions.",
  theory:"## Data Observability\n\n### The 5 Pillars\n1. **Freshness**: Is the data up-to-date? When was the table last updated?\n2. **Volume**: Did the expected number of rows arrive? (Yesterday had 1M, today has 100 — something is wrong).\n3. **Schema**: Did any columns get added, removed, or changed type?\n4. **Distribution**: Are values within expected ranges? (Revenue suddenly negative?).\n5. **Lineage**: Which upstream changes caused this issue?\n\n### Tools\n- **Monte Carlo**: Commercial leader in data observability.\n- **Great Expectations**: Open-source data validation library.\n- **Elementary**: Open-source dbt-native observability.\n- **Soda**: Open-source data quality checks.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["lambda-arch"],previousTopics:["data-lineage"],
  commonMistakes:["Only monitoring pipeline status (green/red) and not the actual data quality"],
  interviewQuestions:["What are the 5 pillars of data observability?","Pipeline success vs data correctness?"],
  flashcards:[{front:"5 Pillars of Data Observability?",back:"1. Freshness 2. Volume 3. Schema 4. Distribution 5. Lineage"}],
  summary:"Data observability monitors the data itself (not just pipelines) across 5 pillars: freshness, volume, schema, distribution, and lineage."
},
{
  id:"cdc",title:"Change Data Capture (CDC)",phase:"concepts",phaseLabel:"Modern DE Concepts",
  description:"Capture only the rows that changed in a source database, instead of re-extracting the entire table every time.",
  difficulty:"intermediate",estimatedHours:3,importance:"must-know",interviewWeight:4,
  careerLevel:"junior",interviewImportance:4,productionImportance:5,
  interviewRecommendation:"Learn Deeply — one of the most frequently asked DE concepts",
  prerequisites:["data-pipeline","batch-vs-streaming"],
  learningObjectives:["Define CDC and its benefits","Compare log-based vs query-based CDC","Understand Debezium + Kafka CDC architecture"],
  problemItSolves:"Your source Postgres table has 500M rows. Extracting ALL 500M rows every night takes 6 hours and costs $200/run. CDC captures only the ~50K rows that changed, reducing the job to 2 minutes.",
  whyItExists:"As databases grow, full-table extractions become prohibitively slow and expensive. CDC enables near-real-time data synchronization.",
  realWorldUsage:"Debezium reads the Postgres WAL (Write-Ahead Log) and streams every INSERT, UPDATE, DELETE to a Kafka topic. A downstream consumer applies these changes to the data warehouse.",
  theory:"## Change Data Capture\n\n### Types of CDC\n1. **Query-Based (Timestamp)**: `SELECT * FROM orders WHERE updated_at > last_run_time`. Simple but misses deletes and has race conditions.\n2. **Log-Based**: Reads the database's transaction log (WAL for Postgres, Binlog for MySQL). Captures ALL changes including deletes. Gold standard.\n3. **Trigger-Based**: Database triggers write changes to a shadow table. Adds overhead to the source DB.\n\n### Log-Based CDC Architecture\n```\nPostgres (WAL) → Debezium → Kafka Topic → Spark/Flink → Delta Lake\n```\n\n### Debezium\nThe open-source standard for log-based CDC. Runs as a Kafka Connect connector. Supports Postgres, MySQL, MongoDB, SQL Server, Oracle.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Set up Debezium with Docker Compose to stream changes from Postgres to a Kafka topic"],
  nextTopics:["kafka-overview"],previousTopics:["batch-vs-streaming"],
  commonMistakes:["Using query-based CDC and missing DELETE operations","Not handling schema changes in the CDC stream"],
  interviewQuestions:["What is CDC?","Query-based vs log-based CDC?","What is Debezium?","How does log-based CDC work with Postgres?"],
  flashcards:[{front:"Query-based vs Log-based CDC?",back:"Query-based: Polls with WHERE updated_at > X. Misses deletes, has race conditions. Log-based: Reads the DB transaction log (WAL/Binlog). Captures all changes including deletes. Preferred."}],
  summary:"CDC captures only changed rows from a source database. Log-based CDC (Debezium) reads the transaction log and is the production standard."
},

// ═══ ARCHITECTURE EXPANSION ═══
{
  id:"lambda-arch",title:"Lambda Architecture",phase:"architecture",phaseLabel:"Modern Data Architecture",
  description:"Understand the dual-pipeline architecture that processes data in both batch and real-time simultaneously.",
  difficulty:"intermediate",estimatedHours:2,importance:"good-to-know",interviewWeight:3,
  careerLevel:"junior",interviewImportance:3,productionImportance:2,
  interviewRecommendation:"Know Concept — historical knowledge, being replaced by Kappa/Lakehouse",
  prerequisites:["batch-vs-streaming","data-warehouse"],
  learningObjectives:["Understand the 3 layers of Lambda Architecture","Identify its problems (code duplication)","Know when Lambda is still used"],
  problemItSolves:"You need both accurate historical analytics (batch) AND real-time dashboards (streaming). Lambda runs both pipelines and merges their results.",
  whyItExists:"Created by Nathan Marz (creator of Apache Storm) in 2011. It was the first architecture to combine batch and streaming.",
  realWorldUsage:"While modern architectures (Kappa, Lakehouse) are preferred, many legacy systems at banks and telecoms still use Lambda.",
  theory:"## Lambda Architecture\n\n### The 3 Layers\n1. **Batch Layer**: Processes ALL historical data periodically (e.g., nightly Spark job). Produces the 'batch view' — accurate but stale.\n2. **Speed Layer**: Processes real-time data as it arrives (e.g., Kafka + Flink). Produces the 'real-time view' — fresh but approximate.\n3. **Serving Layer**: Merges the batch view and real-time view to answer queries.\n\n### The Problem\n**Code Duplication**: You must write the same business logic TWICE — once in Spark (batch) and once in Flink (streaming). Maintaining two codebases for the same logic is a nightmare.\n\n### Why It's Being Replaced\nDelta Lake + Structured Streaming allows a single codebase to handle both batch and streaming (the Lakehouse pattern).",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["kappa-arch"],previousTopics:["lakehouse-arch"],
  commonMistakes:["Choosing Lambda for a new project (use Lakehouse or Kappa instead)"],
  interviewQuestions:["What are the 3 layers of Lambda Architecture?","What is the main problem with Lambda?","Lambda vs Kappa?"],
  flashcards:[{front:"Main problem with Lambda Architecture?",back:"Code duplication. You must write the same business logic twice: once for the batch layer (Spark) and once for the speed layer (Flink)."}],
  summary:"Lambda Architecture uses parallel batch + streaming pipelines merged by a serving layer. Being replaced by Lakehouse/Kappa due to code duplication."
},
{
  id:"kappa-arch",title:"Kappa Architecture",phase:"architecture",phaseLabel:"Modern Data Architecture",
  description:"A streaming-only architecture that eliminates the batch layer entirely.",
  difficulty:"intermediate",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"mid",interviewImportance:2,productionImportance:2,
  interviewRecommendation:"Know Concept — often compared with Lambda in interviews",
  prerequisites:["lambda-arch"],
  learningObjectives:["Understand the Kappa simplification","Know when streaming-only works","Identify limitations of pure Kappa"],
  problemItSolves:"Lambda's code duplication is unsustainable. Kappa says: 'If you can process everything as a stream, why maintain a separate batch system?'",
  whyItExists:"Proposed by Jay Kreps (co-creator of Kafka) in 2014 as a response to Lambda's complexity.",
  realWorldUsage:"Companies with primarily real-time use cases (ad tech, fraud detection) sometimes adopt pure Kappa. Most companies use a hybrid Lakehouse approach.",
  theory:"## Kappa Architecture\n\n### Core Idea\nTreat everything as a stream. If you need to reprocess historical data, replay the Kafka topic from the beginning.\n\n### How Reprocessing Works\n1. Keep all raw data in Kafka with long retention (or infinite retention with tiered storage).\n2. When business logic changes, deploy a new streaming job that reads from offset 0.\n3. The new job reprocesses all historical events with the new logic.\n\n### Limitations\n- Reprocessing from offset 0 can be very slow for large datasets.\n- Complex analytical queries (aggregations over years of data) are still better suited for batch engines.\n- Not practical if Kafka retention is limited.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["data-catalog"],previousTopics:["lambda-arch"],
  commonMistakes:["Trying to use pure Kappa when you have complex historical aggregation requirements"],
  interviewQuestions:["What is Kappa Architecture?","Lambda vs Kappa?","When would you NOT use Kappa?"],
  flashcards:[{front:"Lambda vs Kappa Architecture?",back:"Lambda: Dual pipeline (batch + streaming). Kappa: Streaming only. Kappa is simpler but doesn't handle complex historical analytics well."}],
  summary:"Kappa Architecture processes everything as a stream, eliminating Lambda's code duplication. Limited for complex historical analytics."
},
{
  id:"data-catalog",title:"Data Catalog",phase:"architecture",phaseLabel:"Modern Data Architecture",
  description:"A searchable inventory of all datasets in your organization — the 'Google for your data'.",
  difficulty:"beginner",estimatedHours:1,importance:"good-to-know",interviewWeight:1,
  careerLevel:"mid",interviewImportance:1,productionImportance:3,
  interviewRecommendation:"Know Concept — briefly mentioned in governance discussions",
  prerequisites:["data-governance","metadata"],
  learningObjectives:["Define a data catalog","Know popular catalog tools (DataHub, Atlan, Unity Catalog)","Understand metadata management"],
  problemItSolves:"An analyst asks: 'Do we have customer churn data?' Without a catalog, they email 5 teams and wait 3 days. With a catalog, they search and find the table in seconds.",
  whyItExists:"As companies accumulate hundreds of tables across multiple databases and lakes, discovering and understanding data becomes impossible without a centralized catalog.",
  realWorldUsage:"Databricks Unity Catalog, AWS Glue Catalog, DataHub (open source), and Atlan are the most popular options.",
  theory:"## Data Catalog\n\n### What It Stores\n- **Technical Metadata**: Table names, column types, partitions, locations.\n- **Business Metadata**: Descriptions, owners, tags, classifications.\n- **Operational Metadata**: Last updated, row counts, freshness.\n- **Lineage**: Where data comes from and where it goes.\n\n### Popular Tools\n| Tool | Type | Notes |\n|------|------|-------|\n| Unity Catalog | Databricks Native | Governance + catalog |\n| AWS Glue Catalog | AWS Native | Used with Athena, EMR |\n| DataHub | Open Source | LinkedIn's metadata platform |\n| Atlan | Commercial | Modern, Notion-like UI |",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["csv-json"],previousTopics:["data-governance"],
  commonMistakes:["Building a data catalog but not enforcing data owners to maintain descriptions"],
  interviewQuestions:["What is a data catalog?","Why do organizations need one?"],
  flashcards:[{front:"What is a Data Catalog?",back:"A searchable inventory of all datasets in an organization, storing technical, business, and operational metadata. Think 'Google for your company's data'."}],
  summary:"A data catalog is a searchable inventory of all datasets, enabling data discovery across the organization."
},

// ═══ DISTRIBUTED EXPANSION ═══
{
  id:"replication",title:"Replication & Fault Tolerance",phase:"distributed",phaseLabel:"Distributed Computing",
  description:"Understand how distributed systems copy data across machines to survive hardware failures.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:3,
  careerLevel:"junior",interviewImportance:3,productionImportance:5,
  interviewRecommendation:"Learn Well — fundamental distributed systems knowledge",
  prerequisites:["horizontal-scaling"],
  learningObjectives:["Define replication factor","Understand leader-follower replication","Explain how Kafka and HDFS replicate data"],
  problemItSolves:"If your data is stored on a single server and that server's hard drive fails, your data is gone. Replication copies the data to 2+ other servers so failures don't cause data loss.",
  whyItExists:"Hardware fails constantly at scale. Google found that in a cluster of 10,000 servers, 2-3 servers die EVERY DAY.",
  realWorldUsage:"Kafka default replication factor is 3. HDFS default is also 3. This means every piece of data exists on 3 different machines.",
  theory:"## Replication\n\n### Replication Factor\nThe number of copies of each piece of data. RF=3 means 3 copies on 3 different machines.\n\n### Leader-Follower Model (Kafka)\n- One replica is the **Leader**: handles all reads and writes.\n- Other replicas are **Followers**: passively replicate from the leader.\n- If the leader dies, a follower is promoted to the new leader.\n\n### HDFS Block Replication\n- A 1GB file is split into 128MB blocks.\n- Each block is replicated 3 times across different racks.\n- If a DataNode fails, the NameNode automatically re-replicates the lost blocks.\n\n### Trade-off\nHigher replication = more fault tolerance but more storage cost and write latency.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["cap-theorem"],previousTopics:["horizontal-scaling"],
  commonMistakes:["Setting replication factor to 1 in production (no fault tolerance)"],
  interviewQuestions:["What is replication factor?","How does Kafka handle leader failure?","What is the default HDFS replication factor?"],
  flashcards:[{front:"What happens when a Kafka leader replica dies?",back:"One of the in-sync follower replicas is automatically elected as the new leader. Producers and consumers are redirected. This is why RF >= 3 is recommended."}],
  summary:"Replication copies data across multiple machines for fault tolerance. Standard replication factor is 3 (Kafka, HDFS)."
},
{
  id:"cap-theorem",title:"CAP Theorem (Overview)",phase:"distributed",phaseLabel:"Distributed Computing",
  description:"Understand the fundamental trade-off in distributed systems: Consistency, Availability, and Partition Tolerance.",
  difficulty:"advanced",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"mid",interviewImportance:2,productionImportance:2,
  interviewRecommendation:"Know Concept — occasionally asked in system design interviews",
  prerequisites:["replication"],
  learningObjectives:["State the CAP theorem","Explain why you can only choose 2 of 3","Classify Kafka, Cassandra, and Postgres as CP or AP"],
  problemItSolves:"When designing a distributed system, you must make a conscious choice: do you prioritize always being available (AP) or always being consistent (CP)? You cannot have both during a network partition.",
  whyItExists:"Proven by Eric Brewer in 2000. It formalized what distributed systems engineers had observed in practice.",
  realWorldUsage:"Kafka is CP (consistent — during a leader election, the partition is briefly unavailable). Cassandra is AP (available — it may serve slightly stale data during partitions).",
  theory:"## CAP Theorem\n\n### The 3 Properties\n- **Consistency**: Every read receives the most recent write.\n- **Availability**: Every request receives a response (even if it's stale).\n- **Partition Tolerance**: The system continues to operate despite network partitions.\n\n### The Rule\nIn the presence of a network partition, you must choose either Consistency or Availability. You cannot have both.\n\n### Examples\n| System | Type | Behavior During Partition |\n|--------|------|---------------------------|\n| Postgres (single node) | CA | No partition tolerance |\n| Kafka | CP | Brief unavailability during leader election |\n| Cassandra | AP | Serves potentially stale data |\n| DynamoDB | AP | Eventually consistent reads by default |",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["consistency-models"],previousTopics:["replication"],
  commonMistakes:["Thinking you can have all 3 (C, A, and P) simultaneously"],
  interviewQuestions:["What is the CAP theorem?","Is Kafka CP or AP?","Why can't you have all 3?"],
  flashcards:[{front:"CAP Theorem?",back:"In a distributed system experiencing a network partition, you must choose either Consistency (every read gets the latest write) or Availability (every request gets a response). You cannot have both."}],
  summary:"CAP theorem: during network partitions, distributed systems must choose between consistency and availability. Kafka is CP, Cassandra is AP."
},
{
  id:"consistency-models",title:"Consistency Models",phase:"distributed",phaseLabel:"Distributed Computing",
  description:"Understand strong consistency, eventual consistency, and everything in between.",
  difficulty:"advanced",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"senior",interviewImportance:2,productionImportance:3,
  interviewRecommendation:"Know Concept — relevant for senior system design discussions",
  prerequisites:["cap-theorem"],
  learningObjectives:["Define strong vs eventual consistency","Understand read-after-write consistency","Know which databases use which model"],
  problemItSolves:"After writing a record, a user immediately reads it back and gets the OLD value. This is because the system uses eventual consistency and the write hasn't propagated yet.",
  whyItExists:"Different applications have different tolerance for stale reads. A bank transfer MUST be strongly consistent. A social media 'like' count can be eventually consistent.",
  realWorldUsage:"DynamoDB defaults to eventually consistent reads (cheaper, faster) but offers strongly consistent reads at higher cost.",
  theory:"## Consistency Models\n\n### Strong Consistency\nEvery read always returns the most recent write. Like a single-server database.\n- **Pros**: Simplest mental model.\n- **Cons**: Higher latency, lower availability.\n- **Examples**: Postgres, traditional RDBMS.\n\n### Eventual Consistency\nReads may return stale data, but will eventually converge to the latest write.\n- **Pros**: Higher availability, lower latency.\n- **Cons**: Application must handle stale reads.\n- **Examples**: DynamoDB (default), Cassandra, S3.\n\n### Read-After-Write Consistency\nA user always sees their OWN writes immediately. Other users may see stale data.\n- **Example**: S3 provides read-after-write consistency for new objects.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["data-locality"],previousTopics:["cap-theorem"],
  commonMistakes:["Assuming S3 is strongly consistent for all operations (it is now, since Dec 2020, but many resources still say otherwise)"],
  interviewQuestions:["Strong vs eventual consistency?","When would you choose eventual consistency?"],
  flashcards:[{front:"Strong vs Eventual Consistency?",back:"Strong: Every read returns the latest write (higher latency). Eventual: Reads may be stale but converge over time (lower latency, higher availability). Choose based on business requirements."}],
  summary:"Strong consistency guarantees latest reads but has higher latency. Eventual consistency trades freshness for speed and availability."
},
{
  id:"data-locality",title:"Data Locality",phase:"distributed",phaseLabel:"Distributed Computing",
  description:"The principle of moving computation to where the data lives, rather than moving data to where the computation runs.",
  difficulty:"intermediate",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"junior",interviewImportance:2,productionImportance:4,
  interviewRecommendation:"Know Concept — explains why Spark runs on the same cluster as HDFS",
  prerequisites:["driver-executors","shuffling"],
  learningObjectives:["Define data locality","Understand the network bottleneck","Explain how Spark optimizes for locality"],
  problemItSolves:"Moving 1TB of data over the network takes minutes. Running the code on the machine where the 1TB already lives takes seconds. Data locality eliminates the network bottleneck.",
  whyItExists:"Networks are 10-100x slower than local disk reads. In large-scale processing, network I/O is the #1 bottleneck.",
  realWorldUsage:"Spark's task scheduler tries to assign tasks to executors that have the data on their local HDFS DataNode (PROCESS_LOCAL > NODE_LOCAL > RACK_LOCAL > ANY).",
  theory:"## Data Locality\n\n### The Problem\n- Local disk read: ~500 MB/s\n- Network transfer: ~100 MB/s (shared with other jobs)\n- Moving 1TB over network: ~170 minutes\n- Reading 1TB from local disk: ~34 minutes\n\n### Spark Locality Levels\n| Level | Description | Speed |\n|-------|-------------|-------|\n| PROCESS_LOCAL | Data is in the same JVM (cached) | Fastest |\n| NODE_LOCAL | Data is on the same machine's disk | Fast |\n| RACK_LOCAL | Data is on a different machine in the same rack | Medium |\n| ANY | Data is on a different rack | Slowest |",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["why-spark"],previousTopics:["shuffling"],
  commonMistakes:["Ignoring data locality when configuring Spark clusters (putting Spark executors in a different AZ from the HDFS data)"],
  interviewQuestions:["What is data locality?","What are Spark's locality levels?"],
  flashcards:[{front:"What is Data Locality?",back:"Moving computation to where the data lives, rather than moving data over the network. Spark's task scheduler optimizes for this: PROCESS_LOCAL > NODE_LOCAL > RACK_LOCAL > ANY."}],
  summary:"Data locality runs computation where the data lives to avoid network overhead. Spark optimizes task assignment for maximum locality."
}
];

filtered.push(...newModules);
fs.writeFileSync('src/data/modules.json', JSON.stringify(filtered, null, 2));
console.log('B1-B4: Added ' + newModules.length + ' modules (Concepts+Arch+Distributed). Total: ' + filtered.length);
