const fs = require('fs');
const existingModules = JSON.parse(fs.readFileSync('src/data/modules.json', 'utf8'));
const newIds = ['spark-datasets','lazy-evaluation','tungsten','aqe','spark-window-functions',
  'spark-structured-streaming','spark-ui','spark-debugging','spark-partitioning','spark-sql-deep',
  'spark-broadcast','spark-shuffle-deep'];
const filtered = existingModules.filter(m => !newIds.includes(m.id));

const newModules = [
{
  id:"spark-datasets",title:"Spark Datasets (Typed API)",phase:"spark",phaseLabel:"Apache Spark",
  description:"The type-safe API that combines the best of RDDs (compile-time safety) and DataFrames (Catalyst optimization).",
  difficulty:"intermediate",estimatedHours:2,importance:"good-to-know",interviewWeight:3,
  careerLevel:"junior",interviewImportance:3,productionImportance:3,
  interviewRecommendation:"Know Concept — more relevant for Scala shops",
  prerequisites:["spark-dataframes"],
  learningObjectives:["Understand Dataset[T] vs DataFrame","Know when to use Datasets vs DataFrames","Convert between DataFrames and Datasets"],
  problemItSolves:"DataFrames are untyped — you reference columns as strings ('col_name'). If you misspell a column name, you only find out at RUNTIME. Datasets catch these errors at COMPILE TIME.",
  whyItExists:"DataFrames traded type safety for optimization. Datasets bring back type safety while keeping Catalyst optimization.",
  realWorldUsage:"Datasets are primarily used in Scala. In PySpark (Python), there is no Dataset API — only DataFrames. Most DE interviews focus on DataFrames.",
  theory:"## Spark Datasets\n\n### DataFrame vs Dataset\n- **DataFrame** = `Dataset[Row]` — untyped rows, column access via strings.\n- **Dataset[T]** = Typed rows, access via case class fields.\n\n### Scala Example\n```scala\ncase class Order(id: Long, product: String, amount: Double)\nval orders: Dataset[Order] = spark.read.json(\"orders.json\").as[Order]\norders.filter(_.amount > 100.0) // Compile-time type checking!\n```\n\n### When to Use\n- **Scala projects** needing compile-time safety → Dataset\n- **Python (PySpark)** → DataFrame (Datasets don't exist in Python)\n- **Performance-critical SQL** → DataFrame/SQL (Catalyst optimizes better)",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Convert a DataFrame to a typed Dataset in Scala"],
  nextTopics:["lazy-evaluation"],previousTopics:["spark-dataframes"],
  commonMistakes:["Trying to use Datasets in PySpark (they don't exist)","Using Datasets for everything in Scala (DataFrames are often sufficient)"],
  interviewQuestions:["What is the difference between DataFrame and Dataset?","When would you use Dataset over DataFrame?","Do Datasets exist in PySpark?"],
  flashcards:[{front:"DataFrame vs Dataset?",back:"DataFrame = Dataset[Row] (untyped). Dataset[T] = typed with case class. Datasets provide compile-time type safety but are Scala-only. In PySpark, only DataFrames exist."}],
  summary:"Datasets provide type-safe transformations in Scala. DataFrames (Dataset[Row]) are preferred in PySpark since Datasets don't exist in Python."
},
{
  id:"lazy-evaluation",title:"Lazy Evaluation in Spark",phase:"spark",phaseLabel:"Apache Spark",
  description:"Why Spark doesn't execute your code immediately — and how this enables massive optimization.",
  difficulty:"beginner",estimatedHours:1,importance:"must-know",interviewWeight:4,
  careerLevel:"foundation",interviewImportance:4,productionImportance:5,
  interviewRecommendation:"Learn Deeply — fundamental concept, asked in every Spark interview",
  prerequisites:["transformations-actions"],
  learningObjectives:["Define lazy evaluation","Explain how it enables DAG optimization","Identify triggers (actions) that force execution"],
  problemItSolves:"If Spark executed every operation immediately, it couldn't optimize the execution plan. Lazy evaluation lets Spark see your ENTIRE pipeline before choosing the optimal execution strategy.",
  whyItExists:"By deferring execution, Spark's Catalyst optimizer can rearrange, combine, and eliminate operations before running anything. This often results in 10-100x faster execution.",
  realWorldUsage:"Every Spark program uses lazy evaluation implicitly. You chain transformations (.filter().groupBy().agg()) and nothing runs until you call an action (.show(), .write(), .count()).",
  theory:"## Lazy Evaluation\n\n### How It Works\n```python\n# These are TRANSFORMATIONS — nothing executes yet\ndf = spark.read.parquet('data.parquet')  # Lazy\ndf2 = df.filter(df.age > 18)            # Lazy\ndf3 = df2.groupBy('country').count()    # Lazy\n\n# This is an ACTION — NOW Spark builds the DAG and executes\ndf3.show()  # Triggers execution!\n```\n\n### Why It's Powerful\n1. **Predicate Pushdown**: Spark pushes `filter(age > 18)` into the Parquet reader, reading only matching rows.\n2. **Column Pruning**: If `show()` only needs 2 columns, Spark skips reading the other 50 columns.\n3. **Operation Fusion**: Multiple map operations are fused into a single pass.\n\n### Actions That Trigger Execution\n| Action | What It Does |\n|--------|-------------|\n| `.show()` | Display first rows |\n| `.count()` | Count rows |\n| `.collect()` | Return all rows to driver |\n| `.write()` | Write to storage |\n| `.first()` | Return first row |",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Write a chain of 5 transformations and verify nothing executes until .show()"],
  nextTopics:["dag"],previousTopics:["transformations-actions"],
  commonMistakes:["Calling .collect() on large DataFrames (brings all data to driver, causes OOM)","Not understanding why print(df.filter(...)) doesn't show results (it's still lazy)"],
  interviewQuestions:["What is lazy evaluation in Spark?","Why is lazy evaluation important?","Name 3 actions and 3 transformations.","What is predicate pushdown?"],
  flashcards:[{front:"Transformations vs Actions in Spark?",back:"Transformations (filter, map, groupBy) are lazy — they build a plan. Actions (show, count, write, collect) trigger execution of the entire plan."}],
  summary:"Lazy evaluation defers execution until an action is called, letting Catalyst optimize the entire pipeline before running anything."
},
{
  id:"tungsten",title:"Project Tungsten",phase:"spark",phaseLabel:"Apache Spark",
  description:"Spark's execution engine that bypasses JVM garbage collection with custom memory management and code generation.",
  difficulty:"advanced",estimatedHours:1,importance:"good-to-know",interviewWeight:2,
  careerLevel:"senior",interviewImportance:2,productionImportance:4,
  interviewRecommendation:"Know Concept — shows deep Spark understanding in senior interviews",
  prerequisites:["dag"],
  learningObjectives:["Understand off-heap memory management","Know what whole-stage code generation is","Explain how Tungsten improves CPU efficiency"],
  problemItSolves:"The JVM's garbage collector causes unpredictable pauses during large-scale data processing. Tungsten manages memory manually (off-heap) to avoid GC pressure.",
  whyItExists:"Spark 1.x spent 50% of CPU time on serialization and garbage collection. Tungsten, introduced in Spark 1.4+, reduced this to near-zero.",
  realWorldUsage:"Tungsten is automatically used in all modern Spark (2.x+) DataFrame/SQL operations. You don't need to enable it — it's the default engine.",
  theory:"## Project Tungsten\n\n### 3 Key Optimizations\n1. **Off-Heap Memory**: Manages memory outside the JVM heap using `sun.misc.Unsafe`. No garbage collection overhead.\n2. **Binary Processing**: Operates directly on binary data (bytes) instead of Java objects. Eliminates serialization cost.\n3. **Whole-Stage Code Generation**: Instead of interpreting a query plan row-by-row, Tungsten generates optimized Java bytecode that processes data in tight loops.\n\n### Impact\n- **Before Tungsten**: 50% CPU time on GC + serialization.\n- **After Tungsten**: Nearly 100% CPU time on actual computation.\n\n### How to Verify\nIn Spark UI, look for `WholeStageCodegen` in the Physical Plan — this means Tungsten code generation is active.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:[],
  nextTopics:["aqe"],previousTopics:["dag"],
  commonMistakes:["Thinking Tungsten needs to be manually enabled (it's on by default in Spark 2.x+)"],
  interviewQuestions:["What is Project Tungsten?","How does Tungsten improve Spark performance?","What is whole-stage code generation?"],
  flashcards:[{front:"What is Project Tungsten?",back:"Spark's execution engine that manages memory off-heap (no GC), processes binary data directly (no serialization), and generates optimized bytecode (whole-stage codegen)."}],
  summary:"Tungsten eliminates JVM overhead through off-heap memory, binary processing, and whole-stage code generation. Active by default in modern Spark."
},
{
  id:"aqe",title:"Adaptive Query Execution (AQE)",phase:"spark",phaseLabel:"Apache Spark",
  description:"Spark 3.x's ability to re-optimize the execution plan at runtime based on actual data statistics.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:4,
  careerLevel:"junior",interviewImportance:4,productionImportance:5,
  interviewRecommendation:"Learn Deeply — frequently asked in Spark 3.x interviews",
  prerequisites:["dag","spark-joins"],
  learningObjectives:["Understand runtime re-optimization","Know the 3 AQE features: coalesce, skew join, broadcast conversion","Enable/configure AQE"],
  problemItSolves:"Catalyst optimizes BEFORE execution based on estimated statistics. But estimates can be wildly wrong. AQE fixes the plan MID-EXECUTION using actual data sizes.",
  whyItExists:"Before AQE, a sort-merge join on a 1GB table and a 10MB table would waste resources. Catalyst couldn't know the filtered table was only 10MB until runtime.",
  realWorldUsage:"Enabled by default since Spark 3.2. Three killer features: auto-coalesce small partitions, convert sort-merge to broadcast join at runtime, handle skewed joins.",
  theory:"## Adaptive Query Execution (AQE)\n\n### The 3 Features\n\n#### 1. Coalescing Post-Shuffle Partitions\n```\nBefore AQE: 200 shuffle partitions → 180 are tiny (< 1MB each)\nAfter AQE:  200 → 20 partitions (merged small partitions)\n```\n`spark.sql.adaptive.coalescePartitions.enabled = true`\n\n#### 2. Converting Sort-Merge Join to Broadcast Join\nIf after filtering, one side of a join becomes small enough (< `broadcastThreshold`):\n```\nBefore: Sort-Merge Join (expensive shuffle both sides)\nAfter:  Broadcast Hash Join (no shuffle!)\n```\n\n#### 3. Optimizing Skew Joins\nIf one partition has 10x more data than others:\n```\nBefore: One task takes 60 min, others take 1 min\nAfter:  Skewed partition is split into sub-partitions\n```\n\n### Configuration\n```python\nspark.conf.set('spark.sql.adaptive.enabled', 'true')  # Default in 3.2+\nspark.conf.set('spark.sql.adaptive.skewJoin.enabled', 'true')\n```",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Enable AQE and compare execution plans with and without it"],
  nextTopics:["spark-window-functions"],previousTopics:["dag"],
  commonMistakes:["Not enabling AQE on Spark 3.0-3.1 (it's off by default before 3.2)","Setting shuffle partitions to 200 manually when AQE can auto-coalesce"],
  interviewQuestions:["What is AQE?","Name the 3 AQE optimizations.","How does AQE handle data skew?","When was AQE enabled by default?"],
  flashcards:[{front:"3 AQE Optimizations?",back:"1. Coalesce small post-shuffle partitions. 2. Convert sort-merge join to broadcast join at runtime. 3. Split skewed partitions for balanced execution."}],
  summary:"AQE re-optimizes Spark's execution plan at runtime using actual data statistics. Handles partition coalescing, join conversion, and skew."
},
{
  id:"spark-window-functions",title:"Window Functions in Spark",phase:"spark",phaseLabel:"Apache Spark",
  description:"Perform calculations across rows related to the current row without reducing the number of rows — ranking, running totals, lag/lead.",
  difficulty:"intermediate",estimatedHours:3,importance:"must-know",interviewWeight:5,
  careerLevel:"junior",interviewImportance:5,productionImportance:5,
  interviewRecommendation:"Learn Deeply — asked in 90% of Spark SQL interviews",
  prerequisites:["spark-dataframes"],
  learningObjectives:["Use ROW_NUMBER, RANK, DENSE_RANK","Use LAG, LEAD for previous/next row","Use SUM/AVG OVER for running totals","Define window frames (ROWS BETWEEN)"],
  problemItSolves:"You need to find the top 3 products per category, or calculate a running total of revenue, or find the previous order date for each customer. GROUP BY would collapse the rows — Window functions keep all rows while adding computed columns.",
  whyItExists:"SQL GROUP BY reduces rows to one per group. Window functions let you compute aggregates while preserving every original row.",
  realWorldUsage:"Window functions are the #1 most tested SQL/Spark concept in data engineering interviews. Used daily for ranking, deduplication, and time-series analysis.",
  theory:"## Window Functions\n\n### Syntax\n```sql\nSELECT *,\n  ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) AS rank\nFROM products\n```\n\n### Ranking Functions\n| Function | Behavior for Ties |\n|----------|-------------------|\n| ROW_NUMBER() | 1, 2, 3 (no ties) |\n| RANK() | 1, 1, 3 (skips) |\n| DENSE_RANK() | 1, 1, 2 (no skip) |\n\n### Offset Functions\n```sql\nLAG(column, 1) OVER (ORDER BY date)   -- Previous row value\nLEAD(column, 1) OVER (ORDER BY date)  -- Next row value\n```\n\n### Aggregation Windows\n```sql\nSUM(revenue) OVER (\n  PARTITION BY customer_id\n  ORDER BY date\n  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n) AS running_total\n```\n\n### PySpark\n```python\nfrom pyspark.sql import Window\nfrom pyspark.sql import functions as F\n\nw = Window.partitionBy('category').orderBy(F.desc('revenue'))\ndf.withColumn('rank', F.row_number().over(w))\n```",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Find top 3 products per category using ROW_NUMBER","Calculate running total of daily revenue","Find the time gap between consecutive orders per customer using LAG"],
  nextTopics:["spark-partitioning"],previousTopics:["spark-dataframes"],
  commonMistakes:["Confusing RANK vs ROW_NUMBER vs DENSE_RANK","Using ROW_NUMBER without ORDER BY (non-deterministic results)","Not understanding ROWS BETWEEN vs RANGE BETWEEN"],
  interviewQuestions:["ROW_NUMBER vs RANK vs DENSE_RANK?","How do you find the top N per group?","What is a running total using window functions?","LAG vs LEAD?","How do you deduplicate using window functions?"],
  flashcards:[{front:"ROW_NUMBER vs RANK vs DENSE_RANK?",back:"ROW_NUMBER: 1,2,3 (no ties). RANK: 1,1,3 (skips after ties). DENSE_RANK: 1,1,2 (no skip). Use ROW_NUMBER for deduplication."}],
  summary:"Window functions compute aggregates/rankings across related rows without collapsing them. ROW_NUMBER, LAG/LEAD, and running totals are interview essentials."
},
{
  id:"spark-structured-streaming",title:"Spark Structured Streaming",phase:"spark",phaseLabel:"Apache Spark",
  description:"Process real-time data streams using the same DataFrame/SQL API as batch processing.",
  difficulty:"intermediate",estimatedHours:3,importance:"must-know",interviewWeight:3,
  careerLevel:"mid",interviewImportance:3,productionImportance:4,
  interviewRecommendation:"Learn Well — increasingly important for modern DE roles",
  prerequisites:["spark-dataframes","batch-vs-streaming"],
  learningObjectives:["Set up a streaming query","Understand output modes (append, complete, update)","Handle watermarks and late data","Use triggers"],
  problemItSolves:"You need to process Kafka messages in real-time using Spark, but you don't want to learn a completely different API. Structured Streaming lets you use the same DataFrame API for both batch and streaming.",
  whyItExists:"Before Structured Streaming, Spark had DStreams (RDD-based streaming) which was a completely different API. Structured Streaming unified batch and streaming under DataFrames.",
  realWorldUsage:"Reads from Kafka topics, processes data using DataFrame transformations, and writes to Delta Lake, Kafka, or a database. The standard for streaming in the Databricks ecosystem.",
  theory:"## Structured Streaming\n\n### Basic Pattern\n```python\n# Read stream\ndf = spark.readStream \\\n  .format('kafka') \\\n  .option('subscribe', 'orders') \\\n  .load()\n\n# Transform (same DataFrame API!)\nresult = df.selectExpr('CAST(value AS STRING)') \\\n  .groupBy('product').count()\n\n# Write stream\nresult.writeStream \\\n  .outputMode('complete') \\\n  .format('delta') \\\n  .option('checkpointLocation', '/checkpoints/orders') \\\n  .start()\n```\n\n### Output Modes\n| Mode | Behavior | Use Case |\n|------|----------|----------|\n| Append | Only new rows | Event logs |\n| Complete | Entire result table | Aggregations |\n| Update | Only changed rows | Upserts |\n\n### Watermarks (Late Data)\n```python\ndf.withWatermark('event_time', '10 minutes') \\\n  .groupBy(window('event_time', '5 minutes')).count()\n```\nData arriving more than 10 minutes late is dropped.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:{title:"Real-Time Sales Dashboard",description:"Read simulated sales events from a file source, compute running totals per category using Structured Streaming, and write results to a Delta table.",skills:["Spark","Structured Streaming","Delta Lake"],estimatedHours:3},
  exercises:["Set up a file-based streaming source","Use watermarks to handle late-arriving events"],
  nextTopics:["spark-ui"],previousTopics:["spark-dataframes"],
  commonMistakes:["Forgetting to set checkpointLocation (required for fault tolerance)","Using 'complete' mode without aggregation (errors out)"],
  interviewQuestions:["What is Structured Streaming?","Append vs Complete vs Update mode?","What are watermarks?","How does Structured Streaming achieve exactly-once?"],
  flashcards:[{front:"3 Output Modes in Structured Streaming?",back:"Append: only new rows. Complete: entire result (for aggregations). Update: only changed rows. Append is most common for event logs."}],
  summary:"Structured Streaming uses the same DataFrame API for real-time processing. Supports Kafka, watermarks for late data, and exactly-once via checkpoints."
},
{
  id:"spark-ui",title:"Spark UI & Debugging",phase:"spark",phaseLabel:"Apache Spark",
  description:"Read the Spark Web UI to identify performance bottlenecks: skew, spill, shuffle, and stage failures.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:3,
  careerLevel:"junior",interviewImportance:3,productionImportance:5,
  interviewRecommendation:"Learn Well — practical skill that separates juniors from mids",
  prerequisites:["dag","spark-tuning"],
  learningObjectives:["Navigate the Jobs, Stages, and Tasks tabs","Identify data skew from task duration variance","Spot spill (memory overflow to disk)","Read the SQL/DataFrame execution plan"],
  problemItSolves:"Your Spark job takes 3 hours but you don't know why. The Spark UI shows that 99 out of 100 tasks finish in 10 seconds, but 1 task takes 2.5 hours. That's data skew.",
  whyItExists:"Without visibility into task-level execution, debugging Spark performance is guesswork. The Spark UI makes bottlenecks visible.",
  realWorldUsage:"Every Spark developer checks the Spark UI daily. Databricks provides a similar view in its cluster UI. Key things to check: task duration variance, shuffle read/write sizes, GC time.",
  theory:"## Spark UI\n\n### Key Tabs\n1. **Jobs**: Shows all jobs (triggered by actions). Look for failed jobs.\n2. **Stages**: Shows stages within each job. A stage = a set of tasks that can run in parallel.\n3. **Tasks**: Shows individual task metrics. THIS IS WHERE YOU FIND SKEW.\n\n### Red Flags to Look For\n| Symptom | What to Check | Solution |\n|---------|---------------|----------|\n| 1 task takes 100x longer than others | Data skew | Salting, repartition |\n| 'Spill (Disk)' > 0 | Not enough memory | Increase executor memory |\n| High 'Shuffle Read' | Too much data shuffled | Broadcast join, reduce shuffles |\n| High 'GC Time' | Too many Java objects | Use DataFrame API (Tungsten) |\n\n### Reading the Physical Plan\n```\n== Physical Plan ==\n*(2) HashAggregate(...)\n+- Exchange hashpartitioning(...)      ← SHUFFLE!\n   +- *(1) HashAggregate(...)\n      +- *(1) FileScan parquet [...]    ← FILE READ\n```\nLook for `Exchange` = shuffle. More shuffles = more network I/O.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Run a skewed join and identify the skew in Spark UI","Find the shuffle size in the Stages tab"],
  nextTopics:["spark-debugging"],previousTopics:["spark-tuning"],
  commonMistakes:["Ignoring the Spark UI and blindly adding more resources","Not checking task-level metrics (only looking at stage-level)"],
  interviewQuestions:["How do you identify data skew in Spark UI?","What does 'Spill to Disk' mean?","How do you read a Spark execution plan?"],
  flashcards:[{front:"How to identify data skew in Spark UI?",back:"Go to Stages > Tasks tab. If one task's duration is 10-100x longer than others, it's data skew. The skewed task is processing a much larger partition."}],
  summary:"The Spark UI reveals bottlenecks at the task level. Key diagnostics: task duration variance (skew), spill (memory), shuffle sizes, and GC time."
},
{
  id:"spark-partitioning",title:"Partitioning in Spark",phase:"spark",phaseLabel:"Apache Spark",
  description:"Control how data is distributed across executors — the most impactful Spark tuning technique.",
  difficulty:"intermediate",estimatedHours:2,importance:"must-know",interviewWeight:4,
  careerLevel:"junior",interviewImportance:4,productionImportance:5,
  interviewRecommendation:"Learn Deeply — critical for performance tuning interviews",
  prerequisites:["spark-dataframes","partitions-dist"],
  learningObjectives:["repartition vs coalesce","Set spark.sql.shuffle.partitions","Partition by column for optimized writes","Understand partition count impact"],
  problemItSolves:"200 default shuffle partitions is wrong for most workloads. Too many partitions = overhead from task scheduling. Too few = OOM or slow tasks from large partitions.",
  whyItExists:"The number and distribution of partitions directly determines parallelism, memory usage, and whether your job completes in 5 minutes or 5 hours.",
  realWorldUsage:"Rule of thumb: each partition should be 100-200MB. If you have 100GB of data, use ~500-1000 partitions. Use AQE's auto-coalesce when possible.",
  theory:"## Spark Partitioning\n\n### repartition vs coalesce\n| | repartition(N) | coalesce(N) |\n|---|---|---|\n| Direction | Increase or decrease | Decrease only |\n| Shuffle | Full shuffle | No shuffle (merges locally) |\n| Use case | Need even distribution | Reduce partitions after filter |\n\n### shuffle.partitions\n```python\nspark.conf.set('spark.sql.shuffle.partitions', 200)  # Default\n# For small data (< 10GB): use 20-50\n# For large data (> 100GB): use 500-2000\n# Best: enable AQE auto-coalesce\n```\n\n### Partitioned Writes\n```python\ndf.write.partitionBy('date').format('delta').save('/data/table')\n```\nCreates a folder structure: `/data/table/date=2024-01-01/`, `/data/table/date=2024-01-02/`...\nQueries filtering by date read only the relevant partition.",
  resources:{docs:[],youtube:[],udemy:[],articles:[]},
  miniProject:null,exercises:["Experiment with different partition counts and measure execution time","Write a partitioned Delta table and query it with a filter"],
  nextTopics:["spark-tuning"],previousTopics:["spark-dataframes"],
  commonMistakes:["Using repartition when coalesce would suffice (unnecessary shuffle)","Writing unpartitioned tables (full table scans every query)","Using too many small partitions (task scheduling overhead)"],
  interviewQuestions:["repartition vs coalesce?","What is the default number of shuffle partitions?","How do you decide the right partition count?","What is partition pruning?"],
  flashcards:[{front:"repartition vs coalesce?",back:"repartition(N): full shuffle, can increase or decrease partitions, ensures even distribution. coalesce(N): no shuffle, can only decrease, may create uneven partitions."}],
  summary:"Partitioning controls data distribution across executors. Use repartition for even distribution, coalesce to reduce without shuffle, and partitionBy for optimized storage."
}
];

filtered.push(...newModules);
fs.writeFileSync('src/data/modules.json', JSON.stringify(filtered, null, 2));
console.log('B5 (Spark): Added ' + newModules.length + ' modules. Total: ' + filtered.length);
